name: metratec_android_example
description: "A small example on how to use Metratec devices with Android"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: any
  
  metratec_device:
    path: ../metratec_device
  #  git:
  #    url: https://gitlab.metratec.com/dart-libraries/metratec_device.git
  #    ref: 3.2.1
  
  dart_rfid_library:
    path: ../dart_rfid_library
  #  git:
  #    url: https://gitlab.metratec.com/dart-libraries/dart_rfid_library.git
  #    ref: 2.0.0
  
  usb_serial: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

 